services:
  database:
    image: mysql:8.0
    container_name: remote_lab_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    # LƯU Ý: Cổng này chỉ nên mở khi đang phát triển.
    # Khi triển khai thực tế, hãy comment hoặc xóa dòng này.
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: remote_lab_backend
    restart: unless-stopped
    # SỬA LỖI: Đã xóa khối 'ports' ở đây.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/tung/PRODUCTION1/QUAN_LY_USER:/workspaces
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_NAME: remote_lab
      USER_WORKSPACE_DIR: /workspaces  # Đảm bảo đường dẫn này tồn tại trên máy chủ
      INTERNAL_API_SECRET: ${INTERNAL_API_SECRET} # Thêm secret key cho backend
    depends_on:
      - database

  nginx:
    image: nginx:1.25-alpine
    container_name: remote_lab_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/templates:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  hardware_manager:
    build: ./hardware_manager
    container_name: hardware_manager
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      BACKEND_URL: http://backend:5000
      # TỐI ƯU: Thêm secret key để gọi API nội bộ an toàn.
      INTERNAL_API_SECRET: ${INTERNAL_API_SECRET}
      
  hardware_broker:
    build: ./hardware_broker
    container_name: hardware_broker
    restart: unless-stopped
    # QUAN TRỌNG: Ánh xạ các cổng USB vật lý từ máy chủ vào container
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      #- "/dev/ttyUSB1:/dev/ttyUSB1"
      # Thêm các cổng khác nếu cần...
volumes:
  db_data: